export const endpoints = {
  auth: {
    login: '/auth/login',
    loginMfa: '/auth/login/mfa',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    me: '/auth/me',
    updateProfile: '/auth/me',
    mfaSetup: '/auth/mfa/setup',
    mfaVerify: '/auth/mfa/verify',
  },
  users: {
    list: '/users',
    detail: (id: string) => `/users/${id}`,
    create: '/users',
    update: (id: string) => `/users/${id}`,
    delete: (id: string) => `/users/${id}`,
    roles: (id: string) => `/users/${id}/roles`,
  },
  roles: {
    list: '/roles',
    create: '/roles',
    update: (id: string) => `/roles/${id}`,
    delete: (id: string) => `/roles/${id}`,
    permissions: (id: string) => `/roles/${id}/permissions`,
    allPermissions: '/permissions',
  },
  employees: {
    list: '/employees',
    detail: (id: string) => `/employees/${id}`,
    create: '/employees',
    update: (id: string) => `/employees/${id}`,
    delete: (id: string) => `/employees/${id}`,
    orgChart: '/employees/org-chart',
  },
  attendance: {
    records: '/hr/attendance',
    clockIn: '/hr/attendance/clock-in',
    clockOut: '/hr/attendance/clock-out',
    reports: '/hr/attendance/reports',
  },
  leaves: {
    list: '/hr/leaves',
    create: '/hr/leaves',
    approve: (id: string) => `/hr/leaves/${id}/approve`,
    policies: '/hr/leave-policies',
  },
  payroll: {
    runs: '/payroll',
    items: (runId: string) => `/payroll/${runId}/items`,
    payslip: (id: string) => `/payroll/items/${id}`,
  },
  recruitment: {
    jobPosts: '/hr/recruitment/job-posts',
    candidates: '/hr/recruitment/candidates',
  },
  performance: {
    reviews: '/hr/performance-reviews',
    feedback: '/hr/performance-feedback',
  },
  products: {
    list: '/products',
    detail: (id: string) => `/products/${id}`,
    create: '/products',
    update: (id: string) => `/products/${id}`,
    delete: (id: string) => `/products/${id}`,
    search: '/products/search',
    import: '/products/import',
    categories: '/categories',
  },
  inventory: {
    stockLevels: '/inventory/stock-levels',
    stockByProduct: (id: string) => `/inventory/stock-levels/${id}`,
    adjustments: '/inventory/adjustments',
    transfers: '/inventory/transfers',
    movements: '/inventory/movements',
    lowStock: '/inventory/low-stock',
    counts: '/inventory/counts',
    valuation: '/inventory/valuation',
    warehouses: '/inventory/warehouses',
    locations: (id: string) => `/inventory/warehouses/${id}/locations`,
    bins: (locId: string) => `/inventory/locations/${locId}/bins`,
  },
  procurement: {
    purchaseOrders: '/purchasing/purchase-orders',
    poDetail: (id: string) => `/purchasing/purchase-orders/${id}`,
    poApprove: (id: string) => `/purchasing/purchase-orders/${id}/approve`,
    poReceive: (id: string) => `/purchasing/purchase-orders/${id}/receive`,
    goodsReceipts: '/purchasing/goods-receipts',
    suppliers: '/purchasing/suppliers',
    supplierDetail: (id: string) => `/purchasing/suppliers/${id}`,
    rfqs: '/purchasing/rfqs',
  },
  sales: {
    salesOrders: '/sales/orders',
    soDetail: (id: string) => `/sales/orders/${id}`,
    soApprove: (id: string) => `/sales/orders/${id}/approve`,
    soShip: (id: string) => `/sales/orders/${id}/ship`,
    customers: '/sales/customers',
    customer360: (id: string) => `/sales/customers/${id}/360`,
    leads: '/crm/leads',
    opportunities: '/crm/opportunities',
    updateOpportunityStage: (id: string) => `/crm/opportunities/${id}/stage`,
  },
  accounting: {
    chartOfAccounts: '/accounting/chart-of-accounts',
    accountCreate: '/accounting/chart-of-accounts',
    journals: '/accounting/journals',
    journalCreate: '/accounting/journals',
    journalPost: (id: string) => `/accounting/journals/${id}/post`,
    invoices: '/accounting/invoices',
    invoiceCreate: '/accounting/invoices',
    invoicePayment: (id: string) => `/accounting/invoices/${id}/payment`,
    payments: '/accounting/payments',
    bankAccounts: '/accounting/bank-accounts',
    bankReconciliation: '/accounting/bank/reconciliation',
    taxRates: '/accounting/tax-rates',
    taxReports: '/accounting/tax/reports',
    budgets: '/accounting/budgets',
    financialReports: '/accounting/financial-reports',
  },
  projects: {
    list: '/projects',
    detail: (id: string) => `/projects/${id}`,
    create: '/projects',
    tasks: (id: string) => `/projects/${id}/tasks`,
    taskUpdate: (id: string) => `/tasks/${id}`,
    gantt: (id: string) => `/projects/${id}/gantt`,
    timeEntries: '/projects/time-entries',
    members: (id: string) => `/projects/${id}/members`,
  },
  notifications: {
    list: '/notifications',
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: '/notifications/read-all',
  },
  reports: {
    list: '/reports',
    generate: '/reports/generate',
    scheduled: '/reports/scheduled',
    export: (id: string) => `/reports/${id}/export`,
  },
  documents: {
    upload: '/documents/upload',
    list: '/documents',
    download: (id: string) => `/documents/${id}/download`,
  },
  audit: {
    logs: '/audit-logs',
  },
  system: {
    health: '/admin/health',
    overview: '/admin/overview',
    search: '/search',
  },
  admin: {
    overview: '/admin/overview',
    health: '/admin/health',
    healthCheck: '/admin/health/check',
    healthHistory: '/admin/health/history',
    backups: '/admin/backups',
    backupDetail: (id: string) => `/admin/backups/${id}`,
    backupCreate: '/admin/backups',
    backupDelete: (id: string) => `/admin/backups/${id}`,
    backupRestore: (id: string) => `/admin/backups/${id}/restore`,
    queueSummary: '/admin/queue/summary',
    queueTasks: '/admin/queue/tasks',
    queueTaskRetry: (id: string) => `/admin/queue/tasks/${id}/retry`,
    queueTaskCancel: (id: string) => `/admin/queue/tasks/${id}/cancel`,
    queuePurge: (name: string) => `/admin/queue/${name}/purge`,
    activities: '/admin/activities',
  },
} as const;
