export const endpoints = {
  auth: {
    login: '/auth/login',
    loginMfa: '/auth/login/mfa',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    me: '/auth/me',
    updateProfile: '/auth/me',
  },
  users: {
    list: '/users',
    detail: (id: string) => `/users/${id}`,
    create: '/users',
    update: (id: string) => `/users/${id}`,
    delete: (id: string) => `/users/${id}`,
    roles: (id: string) => `/users/${id}/roles`,
  },
  roles: {
    list: '/roles',
    create: '/roles',
    update: (id: string) => `/roles/${id}`,
    delete: (id: string) => `/roles/${id}`,
    permissions: (id: string) => `/roles/${id}/permissions`,
    allPermissions: '/permissions',
  },
  employees: {
    list: '/employees',
    detail: (id: string) => `/employees/${id}`,
    create: '/employees',
    update: (id: string) => `/employees/${id}`,
    delete: (id: string) => `/employees/${id}`,
    orgChart: '/employees/org-chart',
  },
  attendance: {
    records: '/attendance',
    clockIn: '/attendance/clock-in',
    clockOut: '/attendance/clock-out',
    reports: '/attendance/reports',
  },
  leaves: {
    list: '/leaves',
    create: '/leaves',
    approve: (id: string) => `/leaves/${id}/approve`,
    policies: '/leave-policies',
  },
  payroll: {
    runs: '/payroll-runs',
    items: (runId: string) => `/payroll-runs/${runId}/items`,
    payslip: (id: string) => `/payroll-items/${id}`,
  },
  recruitment: {
    jobPosts: '/recruitment/job-posts',
    candidates: '/recruitment/candidates',
  },
  performance: {
    reviews: '/performance-reviews',
    feedback: '/performance-feedback',
  },
  products: {
    list: '/products',
    detail: (id: string) => `/products/${id}`,
    create: '/products',
    update: (id: string) => `/products/${id}`,
    delete: (id: string) => `/products/${id}`,
    search: '/products/search',
    import: '/products/import',
    categories: '/categories',
  },
  inventory: {
    stockLevels: '/inventory/stock-levels',
    stockByProduct: (id: string) => `/inventory/stock-levels/${id}`,
    adjustments: '/inventory/adjustments',
    transfers: '/inventory/transfers',
    movements: '/inventory/movements',
    lowStock: '/inventory/low-stock',
    counts: '/inventory/counts',
    valuation: '/inventory/valuation',
  },
  warehouses: {
    list: '/warehouses',
    locations: (id: string) => `/warehouses/${id}/locations`,
    bins: (locId: string) => `/locations/${locId}/bins`,
  },
  procurement: {
    purchaseOrders: '/purchase-orders',
    poDetail: (id: string) => `/purchase-orders/${id}`,
    poApprove: (id: string) => `/purchase-orders/${id}/approve`,
    poReceive: (id: string) => `/purchase-orders/${id}/receive`,
    goodsReceipts: '/goods-receipts',
    suppliers: '/suppliers',
    supplierDetail: (id: string) => `/suppliers/${id}`,
    rfqs: '/rfqs',
  },
  sales: {
    salesOrders: '/sales-orders',
    soDetail: (id: string) => `/sales-orders/${id}`,
    soApprove: (id: string) => `/sales-orders/${id}/approve`,
    soShip: (id: string) => `/sales-orders/${id}/ship`,
    customers: '/customers',
    customer360: (id: string) => `/customers/${id}/360`,
    leads: '/leads',
    opportunities: '/opportunities',
    updateOpportunityStage: (id: string) => `/opportunities/${id}/stage`,
  },
  accounting: {
    chartOfAccounts: '/chart-of-accounts',
    accountCreate: '/chart-of-accounts',
    journals: '/journals',
    journalCreate: '/journals',
    journalPost: (id: string) => `/journals/${id}/post`,
    invoices: '/invoices',
    invoiceCreate: '/invoices',
    invoicePayment: (id: string) => `/invoices/${id}/payment`,
    payments: '/payments',
    bankAccounts: '/bank-accounts',
    bankReconciliation: '/bank/reconciliation',
    taxRates: '/tax-rates',
    taxReports: '/tax/reports',
    budgets: '/budgets',
    financialReports: '/financial-reports',
  },
  projects: {
    list: '/projects',
    detail: (id: string) => `/projects/${id}`,
    create: '/projects',
    tasks: (id: string) => `/projects/${id}/tasks`,
    taskUpdate: (id: string) => `/tasks/${id}`,
    gantt: (id: string) => `/projects/${id}/gantt`,
    timeEntries: '/time-entries',
    members: (id: string) => `/projects/${id}/members`,
  },
  notifications: {
    list: '/notifications',
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: '/notifications/read-all',
  },
  reports: {
    list: '/reports',
    generate: '/reports/generate',
    scheduled: '/reports/scheduled',
    export: (id: string) => `/reports/${id}/export`,
  },
  documents: {
    upload: '/documents/upload',
    list: '/documents',
    download: (id: string) => `/documents/${id}/download`,
  },
  audit: {
    logs: '/audit-logs',
  },
  system: {
    health: '/monitoring/health',
    config: '/system-config',
    search: '/search',
  },
  admin: {
    backup: '/backup',
    backupRestore: '/backup/restore',
    queue: '/queue',
    activityLogs: '/activity-logs',
  },
} as const;
